export interface Salary {
  "_id": string
  "employee_id": string,
  "year": string,
  "month": string,
  "base_salary": string,
  "merit_salary": string,
  "absence_days": string
  "sick_leave_days": string,
  "welfare_bonus": string,
  "social_security_total": string,
  "provident_fund_total": string,
  "net_salary": string,
  "status": number,
  "created_at": string,
  "updated_at": string,
  "job_number": string,
  "department": string
}